# Comment
name: LEVI'S DOCKER PIPELINE
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ closed ]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello World"

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
            node-version: 20
            cache: 'npm'

      - name: Install npm
        run: npm ci

      - name: npm tests
        run: npm run test

      - name: npm test coverage
        run: npm run test:coverage

      - name: Build my docker image
        run: |
          docker build -t nellevi/bulletin-board-app:latest .
          
      - name: Test the docker image I made
        run: |
          docker run -d -p 3000:3000 --name bulletin-board-app-test nellevi/bulletin-board-app:latest
          sleep 15 
          curl -f http://localhost:3000 || exit 1 # Check if the app is responding
          docker stop bulletin-board-app-test
          docker rm bulletin-board-app-test

      - name: Log in to Docker Hub, so I can push the image there
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Because I set my docker variables in the repository secrets, I can access them here!!!!

      - name: Push the image to Docker Hub
      # I can literally just use the same syntax I always do
        run: docker push nellevi/bulletin-board-app:latest